enableTelemetry: false

injectEnvironmentFiles:
  - .env.yarn?
  - .env.local?
  - .env?
  - .env.production?

networkConcurrency: 50

nodeLinker: node-modules

npmRegistryServer: "https://registry.yarnpkg.com"

yarnPath: .yarn/releases/yarn-4.4.0.cjs
