enableTelemetry: false

networkConcurrency: 50

nodeLinker: node-modules

npmRegistryServer: 'https://registry.yarnpkg.com'

yarnPath: .yarn/releases/yarn-4.3.0.cjs

injectEnvironmentFiles:
  - .env.yarn?
  - .env.local?
  - .env?
  - .env.production?
